# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.1.0
      with:
        change_path: "src/service"

    - name: 'Nuget Pack'
      env:
        VERSION: ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
      run: dotnet pack 'src/Paygate.Client/Paygate.Client.csproj' --configuration Release -p:PackageVersion=$VERSION

    - name: Prep packages
      run: dotnet nuget add source --username ReddragonLR --password ${{ secrets.PACKAGE_API_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ReddragonLR/index.json"

    - name: 'Nuget push'
      env:
        VERSION: ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
      run: dotnet nuget push "src/Paygate.Client/bin/Release/Paygate.Client.$VERSION.nupkg" --api-key ${{ secrets.PACKAGE_API_TOKEN }} --source "github"